application: app-id
version: dev
runtime: python27
api_version: 1
threadsafe: false

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*\.git/.*)

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  mime_type: image/x-icon

- url: /bacheca.*
  script: bacheca.app

- url: /bacheca/admin/.*
  script: bacheca.app
  login: admin

- url: /admin/.*
  script: main.app
  login: admin

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest

builtins:
- deferred: on